### ISSUE TITLE
Broken link to http://www.isa-tools.org/configurations.html 

### ISSUE THREAD

**Issue by sneumann** [ISA-tools/Configuration-Files#8]
Hi, the https://github.com/ISA-tools/Configuration-Files/blob/master/README.md 
has a broken link to http://www.isa-tools.org/configurations.html 
Yours,
Steffen

**Comment by agbeltran** [comment]
Apologies, this is due to the change to a new ISA website. The correct link is: http://www.isa-tools.org/format/configurations/
